### PR TITLE
Catch an exception when trying to access target's undefined `sources_build_phase`

### LINKED ISSUE #42: error when I try to install.
I'm using Xcode 7.1, but I get this:
Xcode 7.1 bug?

Anaylizing dependencies
Installing ReactiveCocoa swift2 (was )
Configuring CoverPages.xcodeproj
/Users/mgray/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/cocoaseeds-0.5.0/lib/cocoaseeds/core.rb:510:in `block in configure_phase': undefined method`sources_build_phase' for #Xcodeproj::Project::Object::PBXAggregateTarget:0x007f93bb8498f0 (NoMethodError)
    from /Users/mgray/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/cocoaseeds-0.5.0/lib/cocoaseeds/core.rb:509:in `each'
    from /Users/mgray/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/cocoaseeds-0.5.0/lib/cocoaseeds/core.rb:509:in`configure_phase'
    from /Users/mgray/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/cocoaseeds-0.5.0/lib/cocoaseeds/core.rb:108:in `install'
    from /Users/mgray/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/cocoaseeds-0.5.0/lib/cocoaseeds/command.rb:11:in`run'
    from /Users/mgray/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/cocoaseeds-0.5.0/bin/seed:5:in `<top (required)>'
    from /Users/mgray/.rbenv/versions/2.2.0/bin/seed:23:in`load'
    from /Users/mgray/.rbenv/versions/2.2.0/bin/seed:23:in `<main>'

My Seedfile:
target :CoverPages do
  github "ReactiveCocoa/ReactiveCocoa", "swift2", :files => "ReactiveCocoa/Swift/**.{swift,h,m}"
end

### PR DESCRIPTION
**Pull request by devxoul**
Fix #42

### CODE REVIEW

File: lib/cocoaseeds/core.rb [hunk 1]
```diff
@@ -507,8 +507,12 @@ def configure_project
     #
     def configure_phase
       self.project.targets.each do |target|
-        phase = target.sources_build_phase
-        next if not phase
+        begin
+          phase = target.sources_build_phase
+          next if not phase
```
Comment (devxoul) [inline lib/cocoaseeds/core.rb]: Awesome
